// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Comandos de CLI (migrate/introspect) necesitan la conexión directa,
    // sin el pooler en modo transaction (Supabase + Prisma: el pooler de
    // 6543/pgbouncer no soporta algunos comandos DDL que usan las
    // migraciones). El runtime de la app sigue usando DATABASE_URL
    // (pooled) — ver src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
